# golangci-lint 配置

run:
  timeout: 5m
  go: '1.21'

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: false
  govet:
    check-shadowing: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
