run:
  timeout: 5m
  go: '1.21'

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - io.Copy
      - (*net.UDPConn).SetReadBuffer
      - (*net.UDPConn).SetWriteBuffer
      - (*net.UDPConn).SetReadDeadline
      - (*net.UDPConn).SetDeadline
      - (*net.UDPConn).WriteToUDP

issues:
  exclude-use-default: true
